version: 2
jobs:
  run-node-tests:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
  run-code-coverage:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - run: npm install
      - run: ./scripts/coverage.sh
workflows:
  version: 2
  run-node-tests:
    jobs:
      - run-node-tests
  run-code-coverage:
    jobs:
      - run-code-coverage
